micronaut:
  application:
    name: todo

jackson:
  serialization:
    writeDatesAsTimestamps: false

endpoints:
  all:
    path: /management
    enabled: false
    sensitive: true
  health:
    enabled: true
    sensitive: false

datasources:
  default:
    url: jdbc:postgresql://${it.postgresql.host:localhost}:${it.postgresql.port:5432}/todo
    username: postgres
    password: ddbbpassword
    driverClassName: org.postgresql.Driver
    minimumIdle: 1
    maximumPoolSize: 5

flyway:
  datasources:
    default:
